language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  # Specify jruby versions until rvm/rvm#4210 are resolved
  - jruby-9.1.9.0
  - jruby-9.1.10.0

before_install:
  - "gem install bundler"

script:
  - bundle exec rake
  - bundle exec rubocop

branches:
  only: master

sudo: false
